<rule-set name="cheese rules"
    xmlns="http://drools.org/rules"    
    xmlns:java="http://drools.org/semantics/java"
    xmlns:xs="http://www.w3.org/2001/XMLSchema-instance"
    xs:schemaLocation="http://drools.org/rules rules.xsd
    				   http://drools.org/semantics/java java.xsd">

<!--
    <rule name="JavaEditor Probability">
        <parameter identifier="eventHolder">
            <class>de.fu_berlin.inf.focustracker.rating.EventHolder</class>
        </parameter>
        <java:condition>true</java:condition>
        <java:consequence>
        	double p = eventHolder.getPercentageOfMethodVisible() - eventHolder.getOtherValue();
            System.out.println(p);
//            eventHolder.setCalculatedProbability(new Double(p));
            drools.assertObject(new Double(p));
        </java:consequence>
    </rule>
-->    
    <rule name="JavaEditor Selection Changed">
        <parameter identifier="event">
            <class>de.fu_berlin.inf.focustracker.rating.event.EditorSelectionEvent</class>
        </parameter>
        <java:condition>event.getAction() == de.fu_berlin.inf.focustracker.interaction.Action.SELECTED</java:condition>
        <java:consequence><![CDATA[

			double p = 0d;
			double percentageVisible = event.getElementRegion().getPercentageVisible();
        	if(percentageVisible >= 0.9d) {
        		p = 0.75d;
        	} else if (percentageVisible >= 0.5d) {
        			p = 0.5d;
        	} else {
        			p = 0.25d;
        	}
            drools.assertObject(new Double(p));
            
        ]]></java:consequence>
    </rule>
    
    <rule name="JavaEditor Selected Same Element">
        <parameter identifier="event">
            <class>de.fu_berlin.inf.focustracker.rating.event.EditorSelectionEvent</class>
        </parameter>
        <java:condition>event.getAction() == de.fu_berlin.inf.focustracker.interaction.Action.SELECTION_SAME_ELEMENT</java:condition>
        <java:consequence><![CDATA[

        	double p = 0d;
        	if(event.getLastInteraction() != null) {
        		p = event.getLastInteraction().getSeverity();
        	}
            drools.assertObject(new Double(p));
            
        ]]></java:consequence>
    </rule>
    
    <rule name="JavaEditor Visibility Changed">
        <parameter identifier="event">
            <class>de.fu_berlin.inf.focustracker.rating.event.ElementVisibiltyEvent</class>
        </parameter>
        <java:condition>true</java:condition>
        <java:consequence><![CDATA[

        	double p = 0d;
        	if(event.isVisible()) {
				double percentageVisible = event.getElementRegion().getPercentageVisible();
	        	if(percentageVisible >= 0.9d) {
	        		p = 0.75d;
	        	} else if (percentageVisible >= 0.5d) {
	        			p = 0.5d;
	        	} else {
	        			p = 0.25d;
	        	}
        	}
            drools.assertObject(new Double(p));
            
        ]]></java:consequence>
    </rule>
    
</rule-set>