/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class de_fu_berlin_inf_atl_ntps_NTProcess */

#ifndef _Included_de_fu_berlin_inf_atl_ntps_NTProcess
#define _Included_de_fu_berlin_inf_atl_ntps_NTProcess
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     de_fu_berlin_inf_atl_ntps_NTProcess
 * Method:    Initialize
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_de_fu_1berlin_inf_atl_ntps_NTProcess_Initialize
  (JNIEnv *, jclass);

/*
 * Class:     de_fu_berlin_inf_atl_ntps_NTProcess
 * Method:    EnumProcesses
 * Signature: ()[I
 */
JNIEXPORT jintArray JNICALL Java_de_fu_1berlin_inf_atl_ntps_NTProcess_EnumProcesses
  (JNIEnv *, jclass);

/*
 * Class:     de_fu_berlin_inf_atl_ntps_NTProcess
 * Method:    OpenProcess
 * Signature: (I)I
 */
JNIEXPORT jint JNICALL Java_de_fu_1berlin_inf_atl_ntps_NTProcess_OpenProcess
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_fu_berlin_inf_atl_ntps_NTProcess
 * Method:    EnumProcessModules
 * Signature: (I)[I
 */
JNIEXPORT jintArray JNICALL Java_de_fu_1berlin_inf_atl_ntps_NTProcess_EnumProcessModules
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_fu_berlin_inf_atl_ntps_NTProcess
 * Method:    GetModuleFileName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_fu_1berlin_inf_atl_ntps_NTProcess_GetModuleFileName
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_fu_berlin_inf_atl_ntps_NTProcess
 * Method:    GetModuleBaseName
 * Signature: (II)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_de_fu_1berlin_inf_atl_ntps_NTProcess_GetModuleBaseName
  (JNIEnv *, jclass, jint, jint);

/*
 * Class:     de_fu_berlin_inf_atl_ntps_NTProcess
 * Method:    GetProcessMemoryInfo
 * Signature: (I)Lde/fu_berlin/inf/atl/ntps/MemoryInfo;
 */
JNIEXPORT jobject JNICALL Java_de_fu_1berlin_inf_atl_ntps_NTProcess_GetProcessMemoryInfo
  (JNIEnv *, jclass, jint);

/*
 * Class:     de_fu_berlin_inf_atl_ntps_NTProcess
 * Method:    CloseHandle
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_de_fu_1berlin_inf_atl_ntps_NTProcess_CloseHandle
  (JNIEnv *, jclass, jint);

#ifdef __cplusplus
}
#endif
#endif
