package de.fu_berlin.inf.focustracker.interaction;

public enum Action {
	MAIN_WINDOW_ACTIVATED, 
	MAIN_WINDOW_DEACTIVATED, 
	SELECTED, 
	SELECTION_CHANGED, 
	NEIGHBOUR_SELECTED, 
	SELECTION_SAME_ELEMENT, 
	DESELECTED, 
	LOSING_FOCUS,
	VISIBILITY_GAINED,
	VISIBILITY_CHANGED,
	VISIBILITY_LOST,
	FOLDING_COLLAPSED,
	FOLDING_EXPANDED, 
	COLLAPSED, 
	EXPANDED, 
	TEXT_CHANGED, 
	MOUSE_OVER, 
	USER_INACTIVE, 
	USER_ACTIVE, 
	CURSOR_MOVED, 
	PROJECT_OPENED,
	PROJECT_CLOSED, 
	CLASS_OPENED,
	CLASS_CLOSED,
	
	;
}
